import numpy as np
zero_arr = np.zeros((2,3))
print("Zero matrix: ",zero_arr)
one_arr = np.ones((4,5))
print("One matrix: ",one_arr)
full_arr = np.full((4,5),7)
print("Full matrix: ",full_arr)
i_arr = np.eye((4))
print("Identity matrix: ",i_arr)
print()
arr = np.arange(2,10)
print(arr)
print()
arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("Via shape attribute: ",arr1.shape)
print("reshape() method use: ",arr1.reshape(10))